baseURL = "http://justessentials.netlify.app"
languageCode = "en-US"
title = "Just Essentials Marketplace"
disableKinds = ["section"]
pygmentsCodeFences = false
pygmentsUseClasses = false
theme = "mood"

[minify]
  minifyOutput = true

[permalinks]
  post = ":slug/"

[params]
  description = "A minimal just essentials shop"
  keywords = "Stephen Ajulu, shop, moodboard, design inspiration"
  cloudinary_url = "https://res.cloudinary.com/stephenajulu/image/upload/"

[menu]
  [[menu.main]]
    pageRef = "about"
    name = "About"
    url = "/about"
    weight = 5
  [[menu.main]]
    pageRef = "tags"
    name = "Tags"
    url = "/tags"
    weight = 10
